steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: [ 'build', '-t', 'europe-west1-docker.pkg.dev/likeit-prod/docker/likeit:$SHORT_SHA', '.' ]
images:
  - 'europe-west1-docker.pkg.dev/likeit-prod/docker/likeit:$SHORT_SHA'
